export const SITE_CONFIG = {
  name: 'SokoHub',
  developer: 'Asstensha Limited',
  leadDeveloper: 'chris34star',
  currency: 'KSh',
  currencySymbol: 'KSh',
  locale: 'en_KE',
  supportEmail: 'support@sokohub.co.ke',
  whatsappBase: 'https://wa.me/',
};

export const TIER_CONFIG = {
  unverified: {
    label: 'Unverified',
    color: 'gray',
    monthlyPrice: 0,
    maxProducts: 5,
    maxImages: 6,
  },
  verified: {
    label: 'Verified',
    color: 'blue',
    monthlyPrice: 350,
    maxProducts: 50,
    maxImages: 6,
  },
  silver: {
    label: 'Silver',
    color: 'slate',
    monthlyPrice: 1000,
    maxProducts: 200,
    maxImages: 6,
  },
  gold: {
    label: 'Gold',
    color: 'amber',
    monthlyPrice: 2500,
    maxProducts: Infinity,
    maxImages: 6,
  },
} as const;

export const KENYAN_CITIES = [
  'Nairobi',
  'Mombasa',
  'Kisumu',
  'Nakuru',
  'Eldoret',
  'Thika',
  'Malindi',
  'Kitale',
  'Garissa',
  'Kakamega',
  'Machakos',
  'Meru',
  'Nyeri',
  'Kericho',
  'Kilimani',
  'Westlands',
  'Karen',
  'Kikuyu',
  'Rongai',
  'Ruaka',
];

export const NAIROBI_AREAS = [
  'Nairobi CBD',
  'Westlands',
  'Kilimani',
  'Karen',
  'Lavington',
  'Parklands',
  'Ngong Road',
  'Mombasa Road',
  'Thika Road',
  'Langata',
  'Embakasi',
  'Kasarani',
  'Ruaka',
  'Rongai',
  'Kikuyu',
  'South B',
  'South C',
  'Eastleigh',
  'Industrial Area',
];
